"""Views for the resource application."""

# Disable unused import warnings for this file
# flake8: noqa: F401

from .ArrowsResourceGenerator import ArrowsResourceGenerator
from .BarcodeChecksumPosterResourceGenerator import BarcodeChecksumPosterResourceGenerator
from .BinaryCardsResourceGenerator import BinaryCardsResourceGenerator
from .BinaryCardsSmallResourceGenerator import BinaryCardsSmallResourceGenerator
from .BinaryToAlphabetResourceGenerator import BinaryToAlphabetResourceGenerator
from .BinaryWindowsResourceGenerator import BinaryWindowsResourceGenerator
from .GridResourceGenerator import GridResourceGenerator
from .JobBadgesResourceGenerator import JobBadgesResourceGenerator
from .LeftRightCardsResourceGenerator import LeftRightCardsResourceGenerator
from .ModuloClockResourceGenerator import ModuloClockResourceGenerator
from .NumberHuntResourceGenerator import NumberHuntResourceGenerator
from .ParityCardsResourceGenerator import ParityCardsResourceGenerator
from .PianoKeysResourceGenerator import PianoKeysResourceGenerator
from .PixelPainterResourceGenerator import PixelPainterResourceGenerator
from .RunLengthEncodingResourceGenerator import RunLengthEncodingResourceGenerator
from .SearchingCardsResourceGenerator import SearchingCardsResourceGenerator
from .SortingNetworkCardsResourceGenerator import SortingNetworkCardsResourceGenerator
from .SortingNetworkResourceGenerator import SortingNetworkResourceGenerator
from .TrainStationsResourceGenerator import TrainStationsResourceGenerator
from .TreasureIslandResourceGenerator import TreasureIslandResourceGenerator
