# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-31 00:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0093_auto_20190208_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=[], size=None)),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('test_input', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('question_type', models.CharField(max_length=20)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='topics.ProgrammingChallenge')),
            ],
            options={
                'verbose_name': 'Test Case',
            },
        ),
    ]
