broken-link-checker:
  exclude-directories:
    - .git/
    - docs/build/
    - csunplugged/build/
    - csunplugged/node_modules/
    - csunplugged/staticfiles/
    - csunplugged/utils/custom_converter_templates/
  skip-urls:
    # Broken linksthat should not be changed as within license file
    - http://www.zope.org/Resources/ZPL
