project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
project_identifier: cs-unplugged
preserve_hierarchy: true
files: [
  {
    source: csunplugged/locale/en/LC_MESSAGES/*.po,
    translation: csunplugged/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%,
    languages_mapping": {
      two_letters_code: {
        zh-CN: zh_Hans,
        zh-TW: zh_Hant,
      }
    }
  },
  {
    source: csunplugged/topics/content/en/**/*.md,
    translation: csunplugged/topics/content/%two_letters_code%/**/%original_file_name%,
    languages_mapping": {
      two_letters_code: {
        zh-CN: zh_Hans,
        zh-TW: zh_Hant,
      }
    }
  },
  {
    source: csunplugged/topics/content/en/**/*.yaml,
    translation: csunplugged/topics/content/%two_letters_code%/**/%original_file_name%,
    languages_mapping": {
      two_letters_code: {
        zh-CN: zh_Hans,
        zh-TW: zh_Hant,
      }
    }
  },
  {
    source: csunplugged/resources/content/en/*.md,
    translation: csunplugged/resources/content/%two_letters_code%/%original_file_name%,
    languages_mapping": {
      two_letters_code: {
        zh-CN: zh_Hans,
        zh-TW: zh_Hant,
      }
    }
  },
  {
    source: subtitles/en/*.vtt,
    translation: subtitles/%two_letters_code%/%original_file_name%,
    languages_mapping": {
      two_letters_code: {
        zh-CN: zh_Hans,
        zh-TW: zh_Hant,
      }
    }
  },
]
