FROM uccser/django:1.11.14-with-weasyprint

# Add metadata to Docker image
LABEL maintainer="csse-education-research@canterbury.ac.nz"

# Set terminal to be noninteractive
ARG DEBIAN_FRONTEND=noninteractive

ENV DJANGO_PRODUCTION=False
EXPOSE 8080

# Copy and create virtual environment
COPY requirements /requirements

# Install dependencies
RUN /docker_venv/bin/pip3 install -r /requirements/local.txt

RUN mkdir /cs-unplugged/
RUN mkdir /cs-unplugged/csunplugged/
WORKDIR /cs-unplugged/csunplugged/

# Copy and install fonts
COPY csunplugged/static/fonts/ /usr/share/fonts/
RUN fc-cache -fv

# Web Drivers for Selenium Tests
# GeckoDriver v0.19.1
RUN wget -q "https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz" -O /tmp/geckodriver.tgz \
    && tar zxf /tmp/geckodriver.tgz -C /usr/bin/ \
    && rm /tmp/geckodriver.tgz

# chromeDriver v2.35
# RUN wget -q "https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip" -O /tmp/chromedriver.zip \
#    && unzip /tmp/chromedriver.zip -d /usr/bin/ \
#    && rm /tmp/chromedriver.zip

# xvfb - X server display
# ADD xvfb-chromium /usr/bin/xvfb-chromium
# RUN ln -s /usr/bin/xvfb-chromium /usr/bin/google-chrome \
#    && chmod 777 /usr/bin/xvfb-chromium

# create symlinks to chromedriver and geckodriver (to the PATH)
RUN ln -s /usr/bin/geckodriver \
    && chmod 777 /usr/bin/geckodriver
