# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classicpage',
            name='indexed',
        ),
    ]
