# Generated by Django 3.2.11 on 2022-05-20 04:54

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classic', '0003_alter_classicpage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicpage',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='classicpage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='classic_cla_search__3a2336_gin'),
        ),
    ]
