# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-06 04:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=[], size=None)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(default='', max_length=150)),
                ('name_en', models.CharField(default='', max_length=150, null=True)),
                ('name_de', models.CharField(default='', max_length=150, null=True)),
                ('name_es', models.CharField(default='', max_length=150, null=True)),
                ('name_mi', models.CharField(default='', max_length=150, null=True)),
                ('name_zh_hans', models.CharField(default='', max_length=150, null=True)),
                ('name_xx_lr', models.CharField(default='', max_length=150, null=True)),
                ('name_yy_rl', models.CharField(default='', max_length=150, null=True)),
                ('icon', models.CharField(max_length=150, null=True)),
                ('order_number', models.PositiveSmallIntegerField(unique=True)),
                ('introduction', models.TextField(default='')),
                ('introduction_en', models.TextField(default='', null=True)),
                ('introduction_de', models.TextField(default='', null=True)),
                ('introduction_es', models.TextField(default='', null=True)),
                ('introduction_mi', models.TextField(default='', null=True)),
                ('introduction_zh_hans', models.TextField(default='', null=True)),
                ('introduction_xx_lr', models.TextField(default='', null=True)),
                ('introduction_yy_rl', models.TextField(default='', null=True)),
                ('inside_the_computer', models.TextField(default='')),
                ('inside_the_computer_en', models.TextField(default='', null=True)),
                ('inside_the_computer_de', models.TextField(default='', null=True)),
                ('inside_the_computer_es', models.TextField(default='', null=True)),
                ('inside_the_computer_mi', models.TextField(default='', null=True)),
                ('inside_the_computer_zh_hans', models.TextField(default='', null=True)),
                ('inside_the_computer_xx_lr', models.TextField(default='', null=True)),
                ('inside_the_computer_yy_rl', models.TextField(default='', null=True)),
                ('project', models.TextField(default='')),
                ('project_en', models.TextField(default='', null=True)),
                ('project_de', models.TextField(default='', null=True)),
                ('project_es', models.TextField(default='', null=True)),
                ('project_mi', models.TextField(default='', null=True)),
                ('project_zh_hans', models.TextField(default='', null=True)),
                ('project_xx_lr', models.TextField(default='', null=True)),
                ('project_yy_rl', models.TextField(default='', null=True)),
                ('more_information', models.TextField(default='')),
                ('more_information_en', models.TextField(default='', null=True)),
                ('more_information_de', models.TextField(default='', null=True)),
                ('more_information_es', models.TextField(default='', null=True)),
                ('more_information_mi', models.TextField(default='', null=True)),
                ('more_information_zh_hans', models.TextField(default='', null=True)),
                ('more_information_xx_lr', models.TextField(default='', null=True)),
                ('more_information_yy_rl', models.TextField(default='', null=True)),
                ('activity_steps', models.TextField(default='')),
                ('activity_steps_en', models.TextField(default='', null=True)),
                ('activity_steps_de', models.TextField(default='', null=True)),
                ('activity_steps_es', models.TextField(default='', null=True)),
                ('activity_steps_mi', models.TextField(default='', null=True)),
                ('activity_steps_zh_hans', models.TextField(default='', null=True)),
                ('activity_steps_xx_lr', models.TextField(default='', null=True)),
                ('activity_steps_yy_rl', models.TextField(default='', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
