# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-06 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('at_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['order_number']},
        ),
    ]
