# Generated by Django 2.2.12 on 2020-05-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_home', '0004_challenge_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='order_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='challenge',
            unique_together={('activity', 'order_number')},
        ),
    ]
