# Generated by Django 2.2.12 on 2020-05-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_home', '0005_auto_20200529_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project_de',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project_es',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project_mi',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project_xx_lr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project_yy_rl',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project_zh_hans',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
