# Generated by Django 2.2.12 on 2020-06-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_home', '0006_auto_20200529_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_extra_information',
            field=models.TextField(default=''),
        ),
    ]
