# Generated by Django 2.2.12 on 2020-06-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_home', '0007_activity_activity_extra_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_extra_information_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_extra_information_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_extra_information_es',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_extra_information_mi',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_extra_information_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_extra_information_yy_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_extra_information_zh_hans',
            field=models.TextField(default='', null=True),
        ),
    ]
