# Generated by Django 2.2.12 on 2020-06-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_home', '0009_auto_20200602_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='image_description',
            field=models.TextField(default=''),
        ),
    ]
