# Generated by Django 2.2.12 on 2020-10-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_home', '0010_challenge_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesubmission',
            name='encode_key',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='encode_ver',
            field=models.IntegerField(default=-1),
        ),
    ]
