# Generated by Django 2.2.12 on 2021-02-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_home', '0010_challenge_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_extra_information_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_steps_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='inside_the_computer_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='introduction_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='more_information_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='name_fr',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='project_fr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='answer_fr',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='question_fr',
            field=models.TextField(default='', null=True),
        ),
    ]
