# Generated by Django 3.2.11 on 2022-05-20 05:06

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('at_home', '0012_auto_20210929_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='at_home_act_search__0470ab_gin'),
        ),
    ]
