# Generated by Django 3.2.15 on 2022-08-21 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('at_home', '0013_auto_20220520_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_extra_information_xx_lr',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_extra_information_yy_rl',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_steps_xx_lr',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_steps_yy_rl',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='inside_the_computer_xx_lr',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='inside_the_computer_yy_rl',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='introduction_xx_lr',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='introduction_yy_rl',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='more_information_xx_lr',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='more_information_yy_rl',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='name_xx_lr',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='name_yy_rl',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='project_xx_lr',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='project_yy_rl',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='answer_xx_lr',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='answer_yy_rl',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='question_xx_lr',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='question_yy_rl',
        ),
    ]
