#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python manage.py compilemessages
python manage.py rebuild_index --noinput
gunicorn -c ./gunicorn.conf.py -b :8000 config.wsgi --reload
