# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_pin_db_tables'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topic',
            table=None,
        ),
    ]
