# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20170130_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('curriculum_links', models.ManyToManyField(to='topics.CurriculumLink')),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('age_bracket', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('curriculum_links', models.ManyToManyField(to='topics.CurriculumLink')),
                ('learning_outcomes', models.ManyToManyField(to='topics.LearningOutcome')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('scratch_hints', models.TextField()),
                ('scratch_solution', models.TextField()),
                ('python_hints', models.TextField()),
                ('python_solution', models.TextField()),
                ('learning_outcomes', models.ManyToManyField(to='topics.LearningOutcome')),
            ],
        ),
        migrations.CreateModel(
            name='UnitPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.CharField(default='placeholder.png', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
        migrations.AddField(
            model_name='programmingexercise',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.UnitPlan'),
        ),
        migrations.AddField(
            model_name='followupactivity',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
    ]
