# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_auto_20170203_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupactivity',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_activities', to='topics.Topic'),
        ),
    ]
