# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_auto_20170203_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupactivity',
            name='curriculum_links',
            field=models.ManyToManyField(related_name='follow_up_activity_curriculum_links', to='topics.CurriculumLink'),
        ),
        migrations.AlterField(
            model_name='followupactivity',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_follow_up_activities', to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='curriculum_links',
            field=models.ManyToManyField(related_name='lesson_curriculum_links', to='topics.CurriculumLink'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='learning_outcomes',
            field=models.ManyToManyField(related_name='lesson_learning_outcomes', to='topics.LearningOutcome'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_lessons', to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unit_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_plan_lessons', to='topics.UnitPlan'),
        ),
        migrations.AlterField(
            model_name='programmingexercise',
            name='learning_outcomes',
            field=models.ManyToManyField(related_name='programming_exercise_learning_outcomes', to='topics.LearningOutcome'),
        ),
        migrations.AlterField(
            model_name='programmingexercise',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_programming_exercises', to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_unit_plans', to='topics.Topic'),
        ),
    ]
