# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_auto_20170203_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='other_resources',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
