# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_topic_other_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='age_bracket',
            field=models.CharField(max_length=20),
        ),
    ]
