# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0010_auto_20170208_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='age_bracket_slug',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
