# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0011_lesson_age_bracket_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingexercise',
            name='exercise_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
