# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0012_programmingexercise_exercise_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
