# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0013_auto_20170208_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningoutcome',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
