# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0014_learningoutcome_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='classroom_resources',
            field=models.ManyToManyField(related_name='lesson_classroom_resources', to='topics.ClassroomResource'),
        ),
    ]
