# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20170226_0758'),
        ('topics', '0015_auto_20170226_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedGeneratedResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Lesson')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='generated_resources',
            field=models.ManyToManyField(related_name='lesson_generated_resources', through='topics.ConnectedGeneratedResource', to='resources.Resource'),
        ),
    ]
