# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0016_auto_20170226_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='ages',
            field=models.ManyToManyField(related_name='lesson_ages', to='topics.Age'),
        ),
    ]
