# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0017_auto_20170227_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='age_bracket',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='age_bracket_slug',
        ),
    ]
