# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0019_programmingexercisedifficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmingexercisedifficulty',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
