# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0020_auto_20170228_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingexercise',
            name='difficulty',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_programming_exercises', to='topics.ProgrammingExerciseDifficulty'),
            preserve_default=False,
        ),
    ]
