# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0021_programmingexercise_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingExerciseLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingExerciseLanguageSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('hints', models.TextField()),
                ('solution', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='programmingexercise',
            name='python_hints',
        ),
        migrations.RemoveField(
            model_name='programmingexercise',
            name='python_solution',
        ),
        migrations.RemoveField(
            model_name='programmingexercise',
            name='scratch_hints',
        ),
        migrations.RemoveField(
            model_name='programmingexercise',
            name='scratch_solution',
        ),
        migrations.AddField(
            model_name='programmingexerciselanguagesolution',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='topics.ProgrammingExercise'),
        ),
        migrations.AddField(
            model_name='programmingexerciselanguagesolution',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='topics.ProgrammingExerciseLanguage'),
        ),
    ]
