# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0022_auto_20170306_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingexerciselanguage',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
