# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0024_auto_20170306_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingExerciseLanguageImplementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hints', models.TextField()),
                ('solution', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementations', to='topics.ProgrammingExercise')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementations', to='topics.ProgrammingExerciseLanguage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementations', to='topics.Topic')),
            ],
        ),
        migrations.RemoveField(
            model_name='programmingexerciselanguagesolution',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='programmingexerciselanguagesolution',
            name='language',
        ),
        migrations.RemoveField(
            model_name='programmingexerciselanguagesolution',
            name='topic',
        ),
        migrations.DeleteModel(
            name='ProgrammingExerciseLanguageSolution',
        ),
    ]
