# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0026_auto_20170309_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingexercise',
            name='exercise_set_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programmingexercise',
            name='exercise_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
