# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0026_auto_20170309_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumlink',
            name='slug',
            field=models.SlugField(default='default', unique=True),
            preserve_default=False,
        ),
    ]
