# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0027_curriculumlink_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupactivity',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
