# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0028_followupactivity_number'),
        ('topics', '0028_programmingexerciselanguageimplementation_expected_result'),
    ]

    operations = [
    ]
