# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0029_merge_20170316_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('curriculum_links', models.ManyToManyField(related_name='follow_up_activity_curriculum_links', to='topics.CurriculumLink')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_integrations', to='topics.Topic')),
            ],
        ),
        migrations.RemoveField(
            model_name='followupactivity',
            name='curriculum_links',
        ),
        migrations.RemoveField(
            model_name='followupactivity',
            name='topic',
        ),
        migrations.DeleteModel(
            name='FollowUpActivity',
        ),
    ]
