# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0029_merge_20170316_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='CurriculumLink',
            new_name='CurriculumArea',
        ),
        migrations.RemoveField(
            model_name='followupactivity',
            name='curriculum_links',
        ),
        migrations.RemoveField(
            model_name='followupactivity',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='curriculum_links',
        ),
        migrations.AddField(
            model_name='lesson',
            name='curriculum_areas',
            field=models.ManyToManyField(related_name='lesson_curriculum_areas', to='topics.CurriculumArea'),
        ),
        migrations.DeleteModel(
            name='FollowUpActivity',
        ),
        migrations.AddField(
            model_name='curriculumintegration',
            name='curriculum_areas',
            field=models.ManyToManyField(related_name='curriculum_integrations', to='topics.CurriculumArea'),
        ),
        migrations.AddField(
            model_name='curriculumintegration',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_integrations', to='topics.Topic'),
        ),
    ]
