# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0030_auto_20170317_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='programming_exercises',
            field=models.ManyToManyField(related_name='lessons', to='topics.ProgrammingExercise'),
        ),
    ]
