# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0031_lesson_programming_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumintegration',
            name='prerequisite_lessons',
            field=models.ManyToManyField(related_name='curriculum_integrations', to='topics.Lesson'),
        ),
    ]
