# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0034_auto_20170327_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumarea',
            name='parent',
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_curriculum_area', to='topics.CurriculumArea'),
        ),
    ]
