# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0035_auto_20170327_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumarea',
            name='parent',
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='prerequisite_lessons',
            field=models.ManyToManyField(related_name='_curriculumarea_prerequisite_lessons_+', to='topics.CurriculumArea'),
        ),
    ]
