# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0036_auto_20170327_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumarea',
            name='prerequisite_lessons',
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='children',
            field=models.ManyToManyField(related_name='_curriculumarea_children_+', to='topics.CurriculumArea'),
        ),
    ]
