# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0039_auto_20170327_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmingexercise',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='programmingexercise',
            name='difficulty',
            field=models.ManyToManyField(related_name='difficulty_programming_exercises', to='topics.ProgrammingExerciseDifficulty'),
        ),
    ]
