# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0040_auto_20170409_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
