# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0041_lesson_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='classroom_resources',
        ),
        migrations.DeleteModel(
            name='ClassroomResource',
        ),
    ]
