# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0042_auto_20170416_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmingexerciselanguageimplementation',
            name='hints',
            field=models.TextField(null=True),
        ),
    ]
