# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0043_auto_20170416_2355'),
        ('topics', '0040_auto_20170403_0635'),
    ]

    operations = [
    ]
