# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0044_merge_20170423_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmingexercise',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='programmingexercise',
            name='difficulty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_programming_exercises', to='topics.ProgrammingExerciseDifficulty'),
            preserve_default=False,
        ),
    ]
