# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0044_merge_20170423_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningoutcome',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
