# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0045_auto_20170502_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('term', models.CharField(max_length=200, unique=True)),
                ('definition', models.TextField()),
            ],
        ),
    ]
