# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0045_glossarydefinition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlossaryDefinition',
            new_name='GlossaryTerm',
        ),
    ]
