# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0046_glossarydefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingexercise',
            name='extra_challenge',
            field=models.TextField(null=True),
        ),
    ]
