# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0046_glossarydefinition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='curriculum_areas',
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='curriculum_areas',
            field=models.ManyToManyField(related_name='learning_outcomes', to='topics.CurriculumArea'),
        ),
    ]
