# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0046_glossarydefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumarea',
            name='colour',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
