# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0047_curriculumarea_colour'),
        ('topics', '0048_auto_20170507_2226'),
    ]

    operations = [
    ]
