# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0049_merge_20170508_0231'),
        ('topics', '0049_merge_20170508_0247'),
    ]

    operations = [
    ]
