# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 09:05
from __future__ import unicode_literals
from django.contrib.postgres.operations import HStoreExtension
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0050_merge_20170508_0249'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='lesson',
            name='heading_tree',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
