# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0050_merge_20170508_0249'),
        ('topics', '0047_auto_20170507_2105'),
    ]

    operations = [
    ]
