# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 09:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0050_merge_20170508_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='heading_tree',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
