# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0051_merge_20170509_0526'),
        ('topics', '0051_lesson_heading_tree'),
    ]

    operations = [
    ]
