# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 02:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0052_merge_20170510_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitplan',
            name='heading_tree',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
