# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 02:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0053_unitplan_heading_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='classroom_resources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
    ]
