# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0055_programmingexerciselanguage_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmingexerciselanguage',
            old_name='order',
            new_name='number',
        ),
    ]
