# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0056_auto_20170522_0556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningoutcome',
            options={'ordering': ['curriculum_areas__name', 'text']},
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
