# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 23:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0056_auto_20170522_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('age_range', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('unit_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_plan_age_range', to='topics.UnitPlan')),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='min_age',
        ),
        migrations.AddField(
            model_name='lesson',
            name='age_ranges',
            field=models.ManyToManyField(related_name='lesson_age_range', to='topics.AgeRange'),
        ),
    ]
