# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0057_auto_20170529_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='unit_plan',
        ),
    ]
