# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0058_remove_lesson_unit_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='age_ranges',
        ),
        migrations.AddField(
            model_name='agerange',
            name='lessons',
            field=models.ManyToManyField(related_name='lesson_age_range', to='topics.Lesson'),
        ),
    ]
