# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0059_auto_20170530_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agerange',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='agerange',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='agerange',
            name='unit_plan',
        ),
        migrations.AddField(
            model_name='lesson',
            name='age_range',
            field=models.ManyToManyField(related_name='lesson_age_range', to='topics.AgeRange'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit_plan',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='unit_plan_lessons', to='topics.UnitPlan'),
            preserve_default=False,
        ),
    ]
