# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0060_auto_20170530_2141'),
        ('topics', '0060_auto_20170528_0809'),
    ]

    operations = [
    ]
