# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0061_merge_20170603_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
