# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0062_auto_20170609_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(max_length=80),
        ),
    ]
