# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0062_auto_20170609_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('challenge_set_number', models.PositiveSmallIntegerField()),
                ('challenge_number', models.PositiveSmallIntegerField()),
                ('content', models.TextField()),
                ('extra_challenge', models.TextField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ProgrammingExerciseDifficulty',
            new_name='ProgrammingChallengeDifficulty',
        ),
        migrations.RenameModel(
            old_name='ProgrammingExerciseLanguageImplementation',
            new_name='ProgrammingChallengeImplementation',
        ),
        migrations.RenameModel(
            old_name='ProgrammingExerciseLanguage',
            new_name='ProgrammingChallengeLanguage',
        ),
        migrations.RenameModel(
            old_name='ConnectedGeneratedResource',
            new_name='ResourceDescription',
        ),
        migrations.RemoveField(
            model_name='programmingexercise',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='programmingexercise',
            name='learning_outcomes',
        ),
        migrations.RemoveField(
            model_name='programmingexercise',
            name='topic',
        ),
        migrations.RenameField(
            model_name='agerange',
            old_name='age_range',
            new_name='ages',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='programming_exercises',
        ),
        migrations.RemoveField(
            model_name='programmingchallengeimplementation',
            name='exercise',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='age_range',
            field=models.ManyToManyField(related_name='lessons', to='topics.AgeRange'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='generated_resources',
            field=models.ManyToManyField(related_name='lessons', through='topics.ResourceDescription', to='resources.Resource'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='learning_outcomes',
            field=models.ManyToManyField(related_name='lessons', to='topics.LearningOutcome'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unit_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='topics.UnitPlan'),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_plans', to='topics.Topic'),
        ),
        migrations.DeleteModel(
            name='ProgrammingExercise',
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_challenges', to='topics.ProgrammingChallengeDifficulty'),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='learning_outcomes',
            field=models.ManyToManyField(related_name='programming_challenges', to='topics.LearningOutcome'),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_challenges', to='topics.Topic'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='programming_challenges',
            field=models.ManyToManyField(related_name='lessons', to='topics.ProgrammingChallenge'),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='implementations', to='topics.ProgrammingChallenge'),
            preserve_default=False,
        ),
    ]
