# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0063_auto_20170610_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmingchallengeimplementation',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementations', to='topics.ProgrammingChallenge'),
        ),
    ]
