# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0064_auto_20170611_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='computational_thinking_links',
            field=models.TextField(null=True),
        ),
    ]
