# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0067_programmingchallengenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='programming_challenges_temp',
            field=models.ManyToManyField(related_name='lessons_temp', through='topics.ProgrammingChallengeNumber', to='topics.ProgrammingChallenge'),
        ),
    ]
