# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0068_lesson_programming_challenges_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='programming_challenges',
        ),
    ]
