# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0069_remove_lesson_programming_challenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='programming_challenges_temp',
        ),
        migrations.AddField(
            model_name='lesson',
            name='programming_challenges',
            field=models.ManyToManyField(related_name='lessons', through='topics.ProgrammingChallengeNumber', to='topics.ProgrammingChallenge'),
        ),
    ]
