# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0070_auto_20170612_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('age_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.AgeRange')),
            ],
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='number',
            new_name='sorting_number',
        ),
        migrations.AddField(
            model_name='lessonnumber',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='age_range_temp',
            field=models.ManyToManyField(related_name='lessons_temp', through='topics.LessonNumber', to='topics.AgeRange'),
        ),
    ]
