# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0071_auto_20170612_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='age_range',
        ),
    ]
