# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0073_auto_20170612_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agerange',
            options={'ordering': ['ages']},
        ),
    ]
