# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0074_auto_20170613_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonnumber',
            options={'ordering': ['number']},
        ),
    ]
