# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0075_auto_20170613_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='sorting_number',
        ),
    ]
