# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0077_agerange_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='agerange',
            name='slug',
            field=models.SlugField(default='Unset slug'),
            preserve_default=False,
        ),
    ]
