# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0078_agerange_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgeRange',
            new_name='AgeGroup',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='age_range',
            new_name='age_group',
        ),
        migrations.RenameField(
            model_name='lessonnumber',
            old_name='age_range',
            new_name='age_group',
        ),
    ]
