# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 03:06
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0081_unitplan_computational_thinking_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumintegration',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curriculumintegration',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curriculumintegration',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curriculumintegration',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=100),
        ),
        migrations.AddField(
            model_name='curriculumintegration',
            name='name_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curriculumintegration',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curriculumintegration',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='definition_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='definition_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='definition_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=100),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='term_de',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='term_en',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='term_fr',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='heading_tree_de',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='heading_tree_en',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='heading_tree_fr',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=100),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='extra_challenge_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='extra_challenge_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='extra_challenge_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=100),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='name_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='expected_result_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='expected_result_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='expected_result_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='hints_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='hints_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='hints_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=100),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='solution_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='solution_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='solution_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='other_resources_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='other_resources_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='other_resources_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='computational_thinking_links_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='computational_thinking_links_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='computational_thinking_links_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='heading_tree_de',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='heading_tree_en',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='heading_tree_fr',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=100),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
