# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0082_auto_20171017_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='computational_thinking_links_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='computational_thinking_links_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='computational_thinking_links_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='programming_challenges_description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='programming_challenges_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='programming_challenges_description_fr',
            field=models.TextField(null=True),
        ),
    ]
