# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0083_auto_20171019_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='classroom_resources',
        ),
        migrations.AddField(
            model_name='lesson',
            name='classroom_resources',
            field=models.ManyToManyField(to='topics.ClassroomResource'),
        ),
    ]
