# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 00:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0084_auto_20171019_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='description_de',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='description_en',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='description_fr',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=100),
        ),
        migrations.AddField(
            model_name='classroomresource',
            name='description_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classroomresource',
            name='description_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classroomresource',
            name='description_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classroomresource',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=100),
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=100),
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=100),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='text_de',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='text_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='text_fr',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengedifficulty',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=100),
        ),
        migrations.AddField(
            model_name='programmingchallengedifficulty',
            name='name_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengedifficulty',
            name='name_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengedifficulty',
            name='name_fr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengelanguage',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=100),
        ),
        migrations.AddField(
            model_name='resourcedescription',
            name='description_de',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resourcedescription',
            name='description_en',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resourcedescription',
            name='description_fr',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resourcedescription',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=100),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='curriculumarea',
            name='colour',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curriculumarea',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='curriculumintegration',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='curriculumintegration',
            name='content_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='curriculumintegration',
            name='content_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='curriculumintegration',
            name='content_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='curriculumintegration',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='curriculumintegration',
            name='name_de',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='curriculumintegration',
            name='name_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='curriculumintegration',
            name='name_fr',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='term',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='computational_thinking_links',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='computational_thinking_links_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='computational_thinking_links_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='computational_thinking_links_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree_de',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree_en',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree_fr',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name_fr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='programming_challenges_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='programming_challenges_description_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='programming_challenges_description_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='programming_challenges_description_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallenge',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='programmingchallenge',
            name='content_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallenge',
            name='content_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallenge',
            name='content_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallenge',
            name='extra_challenge',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='programmingchallenge',
            name='extra_challenge_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallenge',
            name='extra_challenge_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallenge',
            name='extra_challenge_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallenge',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='programmingchallenge',
            name='name_de',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallenge',
            name='name_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallenge',
            name='name_fr',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallengedifficulty',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='programmingchallengeimplementation',
            name='expected_result',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='programmingchallengeimplementation',
            name='expected_result_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallengeimplementation',
            name='expected_result_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallengeimplementation',
            name='expected_result_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallengeimplementation',
            name='hints',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='programmingchallengeimplementation',
            name='hints_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallengeimplementation',
            name='hints_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallengeimplementation',
            name='hints_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallengeimplementation',
            name='solution',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='programmingchallengeimplementation',
            name='solution_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallengeimplementation',
            name='solution_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallengeimplementation',
            name='solution_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='programmingchallengelanguage',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resourcedescription',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name_fr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='other_resources',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='topic',
            name='other_resources_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='other_resources_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='other_resources_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='computational_thinking_links',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='computational_thinking_links_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='computational_thinking_links_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='computational_thinking_links_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='content_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='content_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='content_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='heading_tree',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='heading_tree_de',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='heading_tree_en',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='heading_tree_fr',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='name_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='name_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='name_fr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
