# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 00:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0084_auto_20171019_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumarea',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=100),
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='name_de',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
