# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0085_auto_20171026_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmingchallengedifficulty',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
