# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 05:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0086_auto_20171108_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agegroup',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='agegroup',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='classroomresource',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='classroomresource',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='curriculumarea',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='curriculumarea',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='curriculumintegration',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='curriculumintegration',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='curriculumintegration',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='curriculumintegration',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='glossaryterm',
            name='definition_de',
        ),
        migrations.RemoveField(
            model_name='glossaryterm',
            name='definition_fr',
        ),
        migrations.RemoveField(
            model_name='glossaryterm',
            name='term_de',
        ),
        migrations.RemoveField(
            model_name='glossaryterm',
            name='term_fr',
        ),
        migrations.RemoveField(
            model_name='learningoutcome',
            name='text_de',
        ),
        migrations.RemoveField(
            model_name='learningoutcome',
            name='text_fr',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='computational_thinking_links_de',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='computational_thinking_links_fr',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='heading_tree_de',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='heading_tree_fr',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='programming_challenges_description_de',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='programming_challenges_description_fr',
        ),
        migrations.RemoveField(
            model_name='programmingchallenge',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='programmingchallenge',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='programmingchallenge',
            name='extra_challenge_de',
        ),
        migrations.RemoveField(
            model_name='programmingchallenge',
            name='extra_challenge_fr',
        ),
        migrations.RemoveField(
            model_name='programmingchallenge',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='programmingchallenge',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='programmingchallengedifficulty',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='programmingchallengedifficulty',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='programmingchallengeimplementation',
            name='expected_result_de',
        ),
        migrations.RemoveField(
            model_name='programmingchallengeimplementation',
            name='expected_result_fr',
        ),
        migrations.RemoveField(
            model_name='programmingchallengeimplementation',
            name='hints_de',
        ),
        migrations.RemoveField(
            model_name='programmingchallengeimplementation',
            name='hints_fr',
        ),
        migrations.RemoveField(
            model_name='programmingchallengeimplementation',
            name='solution_de',
        ),
        migrations.RemoveField(
            model_name='programmingchallengeimplementation',
            name='solution_fr',
        ),
        migrations.RemoveField(
            model_name='programmingchallengelanguage',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='programmingchallengelanguage',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='resourcedescription',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='resourcedescription',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='other_resources_de',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='other_resources_fr',
        ),
        migrations.RemoveField(
            model_name='unitplan',
            name='computational_thinking_links_de',
        ),
        migrations.RemoveField(
            model_name='unitplan',
            name='computational_thinking_links_fr',
        ),
        migrations.RemoveField(
            model_name='unitplan',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='unitplan',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='unitplan',
            name='heading_tree_de',
        ),
        migrations.RemoveField(
            model_name='unitplan',
            name='heading_tree_fr',
        ),
        migrations.RemoveField(
            model_name='unitplan',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='unitplan',
            name='name_fr',
        ),
        migrations.AddField(
            model_name='agegroup',
            name='description_xx_lr',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='description_xx_rl',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='classroomresource',
            name='description_xx_lr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classroomresource',
            name='description_xx_rl',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='name_xx_lr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='name_xx_rl',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curriculumintegration',
            name='content_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='curriculumintegration',
            name='content_xx_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='curriculumintegration',
            name='name_xx_lr',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curriculumintegration',
            name='name_xx_rl',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='definition_xx_lr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='definition_xx_rl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='term_xx_lr',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='term_xx_rl',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='text_xx_lr',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='text_xx_rl',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='computational_thinking_links_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='computational_thinking_links_xx_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_xx_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='heading_tree_xx_lr',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='heading_tree_xx_rl',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_xx_lr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_xx_rl',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='programming_challenges_description_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='programming_challenges_description_xx_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='content_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='content_xx_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='extra_challenge_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='extra_challenge_xx_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='name_xx_lr',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='name_xx_rl',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengedifficulty',
            name='name_xx_lr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengedifficulty',
            name='name_xx_rl',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='expected_result_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='expected_result_xx_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='hints_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='hints_xx_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='solution_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='solution_xx_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengelanguage',
            name='name_xx_lr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengelanguage',
            name='name_xx_rl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resourcedescription',
            name='description_xx_lr',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resourcedescription',
            name='description_xx_rl',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_xx_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_xx_lr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_xx_rl',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='other_resources_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='other_resources_xx_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='computational_thinking_links_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='computational_thinking_links_xx_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='content_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='content_xx_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='heading_tree_xx_lr',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='heading_tree_xx_rl',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='name_xx_lr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='name_xx_rl',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='classroomresource',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='curriculumarea',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='curriculumintegration',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='programmingchallenge',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='programmingchallengedifficulty',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='programmingchallengeimplementation',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='programmingchallengelanguage',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='resourcedescription',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='topic',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=None),
        ),
    ]
