# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0088_auto_20171126_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumarea',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='topics.CurriculumArea'),
        ),
    ]
