# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0089_agegroup_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
