# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-21 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0089_auto_20180118_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingchallenge',
            name='raw_solution',
            field=models.TextField(default=''),
        ),
    ]
