# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 00:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0089_auto_20180118_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='description_de',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='classroomresource',
            name='description_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='name_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curriculumintegration',
            name='content_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='curriculumintegration',
            name='name_de',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='definition_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='term_de',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='text_de',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='computational_thinking_links_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='heading_tree_de',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='programming_challenges_description_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='content_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='extra_challenge_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='name_de',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengedifficulty',
            name='name_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='expected_result_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='hints_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='solution_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengelanguage',
            name='name_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resourcedescription',
            name='description_de',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='other_resources_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='computational_thinking_links_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='content_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='heading_tree_de',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='name_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
