# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-21 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0090_programmingchallenge_raw_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmingchallenge',
            name='raw_solution',
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='raw_solution',
            field=models.TextField(default=''),
        ),
    ]
