# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0090_auto_20171026_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumarea',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='curriculumarea',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='curriculumarea',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='curriculumarea',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
