# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-23 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0091_auto_20180821_2317'),
        ('topics', '0091_auto_20180822_0222'),
    ]

    operations = [
    ]
