# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0092_learningoutcome_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningoutcome',
            name='text_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='text_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='text_fr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
