# Generated by Django 2.2.12 on 2020-06-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0094_auto_20200511_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='text_de',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='text_en',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='text_es',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='text_mi',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='text_xx_lr',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='text_yy_rl',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='text_zh_hans',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
