# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0094_auto_20171026_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomresource',
            name='description_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classroomresource',
            name='description_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classroomresource',
            name='description_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
