# Generated by Django 2.2.12 on 2020-08-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0095_auto_20200603_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingchallenge',
            name='testing_examples',
            field=models.TextField(default=''),
        ),
    ]
