# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 23:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0095_auto_20171026_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomresource',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=100),
        ),
    ]
