# Generated by Django 2.2.12 on 2020-09-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0096_programmingchallenge_testing_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='programming_reminders',
            field=models.TextField(default=''),
        ),
    ]
