# Generated by Django 2.2.12 on 2020-09-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0097_programmingchallengeimplementation_programming_reminders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmingchallengeimplementation',
            name='programming_reminders',
        ),
        migrations.AddField(
            model_name='programmingchallengelanguage',
            name='programming_reminders',
            field=models.TextField(default=''),
        ),
    ]
