# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0097_resourcedescription_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedescription',
            name='description_de',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resourcedescription',
            name='description_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resourcedescription',
            name='description_fr',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
