# Generated by Django 2.2.12 on 2020-09-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0098_auto_20200911_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingchallengelanguage',
            name='programming_reminders_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengelanguage',
            name='programming_reminders_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengelanguage',
            name='programming_reminders_es',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengelanguage',
            name='programming_reminders_mi',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengelanguage',
            name='programming_reminders_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengelanguage',
            name='programming_reminders_yy_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengelanguage',
            name='programming_reminders_zh_hans',
            field=models.TextField(default='', null=True),
        ),
    ]
