# Generated by Django 2.2.12 on 2021-02-15 03:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0099_auto_20200914_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='description_fr',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='classroomresource',
            name='description_fr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='name_fr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curriculumintegration',
            name='content_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='curriculumintegration',
            name='name_fr',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='definition_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='term_fr',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='text_fr',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='computational_thinking_links_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='heading_tree_fr',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_fr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='programming_challenges_description_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='content_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='extra_challenge_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='name_fr',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengedifficulty',
            name='name_fr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='expected_result_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='hints_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengeimplementation',
            name='solution_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengelanguage',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengelanguage',
            name='programming_reminders_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='resourcedescription',
            name='description_fr',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_fr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='other_resources_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='computational_thinking_links_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='content_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='heading_tree_fr',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='name_fr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
