# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0099_auto_20171027_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitplan',
            name='computational_thinking_links',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
