# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 08:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0100_auto_20171027_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroup',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curriculumarea',
            name='colour',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='term',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='computational_thinking_links',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree_de',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree_en',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree_fr',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='programming_challenges_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programmingchallenge',
            name='extra_challenge',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programmingchallengeimplementation',
            name='hints',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='other_resources',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='other_resources_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='other_resources_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='other_resources_fr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='heading_tree',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='heading_tree_de',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='heading_tree_en',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='heading_tree_fr',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
    ]
