# Generated by Django 3.2.11 on 2022-05-16 03:35

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0101_auto_20210929_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='topics_topi_search__d723a2_gin'),
        ),
    ]
