# Generated by Django 3.2.11 on 2022-05-20 04:54

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0103_auto_20220519_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumintegration',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='programmingchallenge',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='curriculumintegration',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='topics_curr_search__ba0181_gin'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='topics_less_search__3c7d6a_gin'),
        ),
        migrations.AddIndex(
            model_name='programmingchallenge',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='topics_prog_search__168ecd_gin'),
        ),
    ]
