# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0104_auto_20171027_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='other_resources',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='topic',
            name='other_resources_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='other_resources_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='other_resources_fr',
            field=models.TextField(default='', null=True),
        ),
    ]
