# Generated by Django 3.2.11 on 2022-06-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0104_auto_20220520_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='unit_plan',
        ),
        migrations.AddField(
            model_name='topic',
            name='computational_thinking_links',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='whats_it_all_about',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='UnitPlan',
        ),
    ]
