# Generated by Django 3.2.11 on 2022-06-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0105_auto_20220609_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='whats_it_all_about_heading_tree',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree_de',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree_en',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree_es',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree_fr',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree_mi',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree_xx_lr',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree_yy_rl',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='heading_tree_zh_hans',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
