# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0107_auto_20171027_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingchallengedifficulty',
            name='name_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengedifficulty',
            name='name_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programmingchallengedifficulty',
            name='name_fr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
