# Generated by Django 3.2.16 on 2022-12-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0108_auto_20220821_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroup',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
