# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0108_auto_20171027_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='text_de',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='text_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='text_fr',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
