# Generated by Django 3.2.16 on 2022-12-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0109_alter_agegroup_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='curriculumintegration',
            constraint=models.UniqueConstraint(fields=('topic', 'number'), name='unique_topic_integration_number'),
        ),
    ]
