# Generated by Django 3.2.16 on 2022-12-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0110_curriculumintegration_unique_topic_integration_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='curriculumintegration',
            constraint=models.UniqueConstraint(fields=('topic', 'slug'), name='unique_topic_integration_slug'),
        ),
    ]
