# Generated by Django 3.2.13 on 2022-06-16 00:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(default='', max_length=200)),
                ('icon', models.CharField(max_length=150, null=True)),
                ('order_number', models.PositiveSmallIntegerField(unique=True)),
                ('introduction', models.TextField(default='')),
                ('video', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
    ]
