# Generated by Django 3.2.13 on 2022-06-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_a_distance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='introduction_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='introduction_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='introduction_es',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='introduction_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='introduction_mi',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='introduction_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='introduction_yy_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='introduction_zh_hans',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_de',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_es',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_fr',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_mi',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_xx_lr',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_yy_rl',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_zh_hans',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
