# Generated by Django 3.2.13 on 2022-07-12 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('at_a_distance', '0002_auto_20220616_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField(unique=True)),
                ('text', models.TextField()),
                ('url', models.URLField()),
                ('language', models.CharField(max_length=10)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_resources', to='at_a_distance.lesson')),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
    ]
