# Generated by Django 3.2.13 on 2022-07-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_a_distance', '0003_supportingresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingresource',
            name='order_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
