# Generated by Django 3.2.13 on 2022-07-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_a_distance', '0004_alter_supportingresource_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='suitable_for_teaching_educators',
            field=models.CharField(choices=[('not-suitable', 'Not suitable'), ('suitable', 'Suitable'), ('not-recommended', 'Not recommended')], default='not-suitable', max_length=15),
        ),
        migrations.AddField(
            model_name='lesson',
            name='suitable_for_teaching_students',
            field=models.CharField(choices=[('not-suitable', 'Not suitable'), ('suitable', 'Suitable'), ('not-recommended', 'Not recommended')], default='not-suitable', max_length=15),
        ),
    ]
