# Generated by Django 3.2.13 on 2022-07-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_a_distance', '0005_auto_20220726_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
