"""URL redirect routing for the Classic CS Unplugged website."""

from django.urls import path
from classic import views

app_name = 'classic'
urlpatterns = [
    path(
        'activities',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'artificial-intelligence',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'binary-numbers',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'books',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'changelog',
        views.redirect_to_changelog,
    ),
    path(
        'class-simulation-computer-unfinished',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'community',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'community-activties',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'contact-us/',
        views.redirect_to_contact,
    ),
    path(
        'contribute',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'cryptographic-protocols',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'curriculum-links',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'databases',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'divideandconquer',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'dominating-sets',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'error-detection',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'events',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'finite-state-automata',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'graph-colouring',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'harold-the-robot-2',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'human-interface-design',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'image-representation',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'information-hiding',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'information-theory',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'line-drawing',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'minimal-spanning-trees',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'modem/',
        views.redirect_to_modems_unplugged,
    ),
    path(
        'modems-unplugged-2',
        views.redirect_to_modems_unplugged,
    ),
    path(
        'network-protocols',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'phylogenetics',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'programming-languages',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'projects',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'promotional',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'public-key-encryption',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'research',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'routing-and-deadlock',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'scout-patrol-encryption',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'searching-algorithms',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'sneak-peek/',
        views.redirect_to_homepage,
    ),
    path(
        'sorting-algorithms',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'sorting-networks',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'steiner-trees',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'teachers',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'text-compression',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'the-turing-test',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'translations',
        views.redirect_to_classic_unplugged,
    ),
    path(
        'videos',
        views.redirect_to_classic_unplugged,
    ),
    # All media files
    path(
        'wp-content<path:media_path>',
        views.redirect_to_classic_unplugged,
    ),
]
