"""URL redirect routing for the Classic CS Unplugged website."""

from django.conf.urls import url
from classic import views


urlpatterns = [
    url(
        r"^activities",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^artificial-intelligence",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^binary-numbers",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^books",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^changelog",
        views.redirect_to_changelog,
    ),
    url(
        r"^class-simulation-computer-unfinished",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^community",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^community-activties",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^contact-us/",
        views.redirect_to_contact,
    ),
    url(
        r"^contribute",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^cryptographic-protocols",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^curriculum-links",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^databases",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^divideandconquer",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^dominating-sets",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^error-detection",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^events",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^finite-state-automata",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^graph-colouring",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^harold-the-robot-2",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^human-interface-design",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^image-representation",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^information-hiding",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^information-theory",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^line-drawing",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^minimal-spanning-trees",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^modem/",
        views.redirect_to_modems_unplugged_2,
    ),
    url(
        r"^modems-unplugged-2",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^network-protocols",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^phylogenetics",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^programming-languages",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^projects",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^promotional",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^public-key-encryption",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^research",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^routing-and-deadlock",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^scout-patrol-encryption",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^searching-algorithms",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^sneak-peek/",
        views.redirect_to_homepage,
    ),
    url(
        r"^sorting-algorithms",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^sorting-networks",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^steiner-trees",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^teachers",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^text-compression",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^the-turing-test",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^translations",
        views.redirect_to_classic_unplugged,
    ),
    url(
        r"^videos",
        views.redirect_to_classic_unplugged,
    ),
    # All media files
    url(
        r"^wp-content/",
        views.redirect_to_classic_unplugged,
    ),
]
