# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('template', models.CharField(max_length=100)),
                ('url_name', models.CharField(max_length=100)),
            ],
        ),
    ]
