# Generated by Django 3.2.11 on 2022-05-20 05:01

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_generalpage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpage',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='generalpage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='general_gen_search__2e3762_gin'),
        ),
    ]
