# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='thumbnail',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
