# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20170306_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='custom_header',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
