# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_resource_custom_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='custom_header',
        ),
    ]
