# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_remove_resource_custom_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='copies',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
