# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_resource_copies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='generation_view',
            new_name='generator_module',
        ),
    ]
