# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 23:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20171020_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='webpage_template',
        ),
        migrations.AddField(
            model_name='resource',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resource',
            name='content_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], size=None),
        ),
        migrations.AddField(
            model_name='resource',
            name='name_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
