# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 20:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20171121_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='content_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='content_yy_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='name_xx_lr',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='name_yy_rl',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=[], size=None),
        ),
    ]
