# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_auto_20171126_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='content_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='name_de',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
