# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_auto_20180817_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='content_es',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='name_es',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
