# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-05 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_auto_20180822_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='thumbnail_static_path',
        ),
    ]
