# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_remove_resource_thumbnail_static_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='content_zh_hans',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='name_zh_hans',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
