# Generated by Django 2.2.12 on 2021-02-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_auto_20200511_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='content_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='name_fr',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
