# Generated by Django 3.2.15 on 2022-08-21 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_auto_20220520_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='content_xx_lr',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='content_yy_rl',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name_xx_lr',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name_yy_rl',
        ),
    ]
