#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py migrate
python /app/manage.py compilemessages
python /app/manage.py rebuild_index --noinput
gunicorn -c /app/gunicorn.conf.py -b :8000 config.wsgi --reload
