#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py migrate
python /app/manage.py compilemessages
gunicorn -c /app/gunicorn.conf.py --bind 0.0.0.0:8000 --log-level 'debug' config.wsgi
